loader:
#  doc_path: '../input_example.zip'
  # loader_name: 'PDFLoader'
  loader_name: 'WordDocumentLoader'
  parsing_params:
    parsing_scheme: 'paragraphs'
    extract_images: False
    extract_tables: False
    parse_formulas: False
    remove_service_info: True
    handle_converting_error: False


splitter:
  splitter_name: 'hierarchical_merger'
  splitter_params:
    chunk_size: 256
    chunk_overlap: 0
    keep_separator: False
    add_start_index: False
    strip_whitespace: True
    apply_chunks_merge: True

# tokenizer: 'hf-internal-testing/llama-tokenizer'
# tokenizer: 'meta-llama/Meta-Llama-3-8B-Instruct'
tokenizer: 'intfloat/multilingual-e5-large'