from modules.variables.prompts.buildings_prompt import buildings_sys_prompt
from modules.variables.prompts.strategy_prompt import accessibility_sys_prompt, strategy_sys_prompt
from modules.variables.prompts.prompt_templates import llama_70b_template, llama_8b_template, all_gpt_template