possible_tables = {
    "city": "General context - general summary for the city",
    "district": "Territorial context - summary for the district or municipality",
    "block": "Territorial context - summary for the block",
    "education": "Sectoral context - education",
    "healthcare": "Sectoral context - healthcare",
    "culture": "Sectoral context - culture and leisure",
    "sport": "Sectoral context - physical culture and sports",
    "government_services": "Sectoral context - public services",
    "demography": "Sectoral context - demography",
    "recreation": "Sectoral context - recreation",
    "transport": "Sectoral context - transport",
    "housing_services": "Sectoral context - housing and utilities",
    "object": "Objects - summary for the selected object",
}

possible_table_indicators = [
    "Population size",
    "Resident population of the territory",
    "Total area of residential premises per capita on average",
    "Share of dilapidated and emergency housing stock in the total housing stock",
    "Population provision with recreational zones",
    "Population provision with playgrounds",
    "Population provision with polyclinics",
    "Population provision with hospitals",
    "Population provision with trauma departments",
    "Population provision with maternity homes",
    "Population provision with educational facilities",
    "Population provision with kindergartens",
    "Population provision with schools",
    "Population provision with healthcare facilities",
    "Average correspondence time in the city by public transport",
    "Pedestrian accessibility of public transport stops",
    "Average correspondence time in the city by personal transport",
    "Average accessibility of the city center",
    "Average accessibility time of healthcare facilities",
    "Average accessibility time of Orthodox churches and temples",
    "Population provision with cultural and leisure facilities",
    "Population provision with sports infrastructure",
    "Total area of residential premises",
    "Share of residential buildings with central cold water supply",
    "Share of residential buildings with central hot water supply",
    "Share of residential buildings with central sewage system",
    "Average accessibility time of maternity homes",
    "Average accessibility time of kindergartens",
    "Average accessibility time of schools",
    "Average correspondence time in the district by public transport",
    "Average correspondence time in the district by personal transport",
    "Population younger than working age",
    "Working-age population",
    "Population older than working age",
    "Population growth in the territory over the last year",
    "Number of preschool children",
    "Number of school-age children",
    "Number of pensioners by age",
    "Average age of residential buildings in the area",
    "Number of emergency residential buildings in the area",
    "Average correspondence time by public transport",
    "Average correspondence time by personal transport",
    "Population provision with secondary special educational institutions",
    "Population provision with higher educational institutions",
    "Average accessibility of polyclinics by public transport",
    "Average accessibility of polyclinics by personal transport",
    "Average pedestrian accessibility of polyclinics",
    "Average accessibility of children's polyclinics by public transport",
    "Average accessibility of children's polyclinics by personal transport",
    "Average pedestrian accessibility of children's polyclinics",
    "Average accessibility of hospitals by personal transport",
    "Average accessibility of trauma departments by public transport",
    "Average accessibility of trauma departments by personal transport",
    "Average pedestrian accessibility of trauma departments",
    "Population provision with dental clinics",
    "Average accessibility time of dental clinics by public transport",
    "Average accessibility time of dental clinics by personal transport",
    "Population provision with women's consultations",
    "Average accessibility time of women's consultations by public transport",
    "Average accessibility time of women's consultations by personal transport",
    "Average pedestrian accessibility of women's consultations",
    "Average pedestrian accessibility of pharmacies",
    "Population provision with ambulance stations",
    "Average accessibility time of children's hospitals by personal transport",
    "Population provision with libraries",
    "Average pedestrian accessibility of libraries",
    "Population provision with museums",
    "Average pedestrian accessibility of museums",
    "Average accessibility time of the circus",
    "Average accessibility time of theaters",
    "Average accessibility time of the zoo",
    "Population provision with cinemas",
    "Average pedestrian accessibility of cafes and restaurants",
    "Average accessibility time of cafes and restaurants by transport",
    "Population provision with swimming pools",
    "Average accessibility time of swimming pools by personal transport",
    "Average accessibility time of swimming pools by public transport",
    "Population provision with gyms",
    "Average accessibility time of gyms by personal transport",
    "Average accessibility time of gyms by public transport",
    "Average pedestrian accessibility of grocery stores",
    "Average pedestrian accessibility of clothing and footwear stores",
    "Average accessibility time of appliance stores by personal transport",
    "Average accessibility time of bookstores by personal transport",
    "Average pedestrian accessibility of children's goods stores",
    "Average accessibility time of children's goods stores by public transport",
    "Average accessibility time of children's goods stores by personal transport",
    "Average accessibility time of bank branches by personal transport",
    "Average pedestrian accessibility of multifunctional centers for public and municipal services",
    "Average accessibility time of multifunctional centers for public and municipal services by public transport",
    "Average accessibility time of multifunctional centers for public and municipal services by personal transport",
    "Average pedestrian accessibility of hairdressers and beauty salons",
    "Average accessibility time of veterinary clinics by personal transport",
    "Average pedestrian accessibility of dog walking areas",
    "Average accessibility time of beaches by transport",
    "Average pedestrian accessibility of embankments",
    "Average pedestrian accessibility of parks",
    "Expected number of pregnant women",
]
